default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: lively_development

test:
  <<: *default
  database: lively_test

production:
  <<: *default
  database: lively_production
